### ISSUE TITLE
Shopify-by-littledata uses the wrong slug in Source catalog 

### ISSUE THREAD

**Issue by sanscontext** [segmentio/segment-docs#401]
As seen in #400 and reported elsewhere
The Sources catalog is for some reason looking for the slug `shopify-by-littledata` while the actual slug of the integration is `shopify-littledata`.

I'm not sure where we're pulling this slug from the Config API:
```yml
- display_name: Shopify (by Littledata)
  slug: shopify-by-littledata
  name: catalog/sources/shopify-littledata
```
