### ISSUE TITLE
Mismatched names and slugs prevent `integration-foot` content from showing

### ISSUE THREAD

**Issue by sanscontext** [segmentio/segment-docs#406]
I'm not quite sure where we're getting the `slug` in the destination catalog script from, but it seems to be bringing in misleading information? In two cases this is preventing the `integration-foot` content from building into the page. Do we remember what the purpose of the `slug` was here? It's not what the app-catalog links are pointing to.

Looking at: 
```yml
- display_name: Google Ads (Gtag)
  slug: google-ads-gtag
  name: catalog/destinations/google-adwords-new
```
https://segment.com/docs/connections/destinations/catalog/google-ads-gtag/ (stub page)
https://segment.com/docs/connections/destinations/catalog/google-adwords-new/ (real page)

```yml
- display_name: Criteo App & Web Events
  slug: criteo-app-web-events
  name: catalog/destinations/criteo
```
https://segment.com/docs/connections/destinations/catalog/criteo-app-web-events/ (stub page)
https://segment.com/docs/connections/destinations/catalog/criteo (real page)
