### ISSUE TITLE
No Personas or Methods booleans available for use with xyzzy.md

### ISSUE THREAD

**Issue by AaronAtSegment** [segmentio/segment-docs#565]
I'd like to update the xyzzy.md script to include whether a destination is a Personas destination. I don't know the exact logic for how our docs know if a destination is a Personas destination, so if we can find that it would be great!

I think that in order to do this, we need the destinations.yml file to contain the methods (provided by the API response) for each destination along with the components and platforms that already are in this file.

Current destination example:
```
components:
  - type: WEB
  platforms:
    browser: true
    server: false
    mobile: false
  browserUnbundlingSupported: false
  browserUnbundlingPublic: true
```

Requested destination example:
```
components:
  - type: WEB
  platforms:
    browser: true
    server: false
    mobile: false
  browserUnbundlingSupported: false
  browserUnbundlingPublic: true
  methods:
    track: true
    identify: false
    page: false
    group: true
    alias: false
```

### Problem location

I think the /src/_data/catalog/destinations.yml file is the culprit, and I think this is generated by /scripts/catalog.js

### Suggestions for a fix

I've submitted a suggested fix to pull in the methods, but I'm unable to verify locally because when I run the script, my destinations.yml file is not being updated. https://github.com/segmentio/segment-docs/pull/564

### Mood (optional)

Excited!
