### ISSUE TITLE
Empty Source "Project Source" probably shouldn't be live

### ISSUE THREAD

**Issue by AaronAtSegment** [segmentio/segment-docs#572]
### What's wrong? Describe the what you're seeing

There is an empty page for a source called "Project Source". There is a description and type in the sources.yml catalog file but no category. Here's what it says in the .yml file:
```
- display_name: Project
  slug: project
  name: catalog/sources/project
  description: >-
    We suggest that you create one source for each type of data you want to
    collect (a website, a mobile app etc.)  If you have a special reason to want
    a single write key to send multiple types of event data to, you can create a
    Legacy Project.
  url: connections/sources/catalog/cloud-apps/project
  logo:
    url: 'https://d3hotuclm6if1r.cloudfront.net/logos/project-default.svg'
  mark:
    url: ''
  categories: []
  type: event
```

### Problem location

https://segment.com/docs/connections/sources/catalog/cloud-apps/project/

### Suggestions for a fix

unknown

### Mood (optional)

:)
